# pytest.ini
[pytest]
minversion = 6.0
addopts = -ra -q --html=../report/report.html --self-contained-html --alluredir=../report/allure-results --log-file=../logs/pytest.log allure generate allure-results -o allure-report --clean
# testpaths = C:/Users/Si Zhang/arm
log_cli = true
# log_cli_level = INFO

